import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>

      </head>     
      <ReduxProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <GoogleOAuthProvider clientId="333199645617-3k617ptkskg5vp2b3342gffi8jq344n6.apps.googleusercontent.com">
        <Header/>
        {children}
        <Footer/>
        <Script
         src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"
          strategy="lazyOnload" // Options: 'beforeInteractive', 'afterInteractive', 'lazyOnload'
        />
        </GoogleOAuthProvider>
      </body>
      </ReduxProvider>
    </html>
  );
}
